### ISSUE TITLE
When publishing a service, and using the Get operation with ChangeLog enable, references are not included

### ISSUE THREAD

**Issue by jaspervanderhoek** [mendix/RestServices#52]
when an object is retrieved through the default get service:  rest/orders/12312312

the json below is returned. 
{
    "Comments": "Empty test case", "Value": 20.22,"OrderDate": 1425920400000,"OrderNumber": 290831079,
    "OrderLines": [
        {
            "Quantity": 1,
            "LineNumber": null,
            "Product": "Product1",
            "LinePrice": 10.99
        }
    ]
}

However when using the ChangeLog, the index that was created does not contain any references. The microflow behaves correct and serializes the correct information without the changelog. But the changelog never contains my orderline information.

The same order in the indexed object list looks like this:
{
    "Comments": "Empty test case",
    "Value": 20.22,
    "OrderDate": 1425920400000,
    "OrderNumber": 290831079,
    "OrderLines": [ ]
}

**Comment by mweststrate** [comment]
Hi Jasper, 

Which Mendix version are you using?

**Comment by jaspervanderhoek** [comment]
This was in 5.9.1 with the version from github from last Monday.

**Comment by mweststrate** [comment]
Some notes: The same serialization process as in normal calls is used.

Possible cause: 
publish/ChangeLogManager.publishUpdate needs to wrap its code in a utils.withSessionCache. If references don't resolve, missing (already dropped) entries in the session cache are usually the cause.   

also: add tests with reference to test/ChangeTests.java
