### ISSUE TITLE
UTF-8 Byte Order Mark (BOM)

### ISSUE THREAD

**Issue by ArthurvdMolen** [mendix/RestServices#53]
When a JSON server issues an UTF-8 Byte Order Mark (BOM) the validation will fail within the restservices. I have fixed not the issue but could mendix just ignore it like browsers?

see example:

https://groups.google.com/forum/#!topic/golang-nuts/OToNIPdfkks

**Comment by mweststrate** [comment]
Thanks for reporting, I'll consider this definitly for the next release. In the mean time, do you happen to have a ready to use fix / work around for this?

**Comment by ArthurvdMolen** [comment]
Yes, i found the issue and fixed it. Application is an JSON libray we build for Wordpress and we fixed to code there but I think Mendix should be able to deal with BOM's I suppose you apply some sort of open source library or is all code Mendix build?

**Comment by mweststrate** [comment]
Ideally we should be able to deal with it. Rest services relies heavily on Apache commons, so probably there is something in there.

**Comment by mweststrate** [comment]
Published
