### ISSUE TITLE
Generated documentation doesn't work at POST methods.

### ISSUE THREAD

**Issue by ArjenLammers** [mendix/RestServices#58]
When going to the generated documentation (e.g. /rest) all services are listed.
When I select a service that should only accept a POST, I get a METHOD_NOT_ALLOWED error.
For documentation I expect this to work through my normal browser interface.

**Comment by mweststrate** [comment]
Also see: https://mxforum.mendix.com/questions/8684/Inlog-REST-in-browser-

Proposed solutions: disable these links.

**Comment by mweststrate** [comment]
Confirmed the bug, but the generation of those links is quite generic and I don't think it is worth the additional setup needed for a developers convenience thingy. So a `wontfix` for now.
