### ISSUE TITLE
Keep receiving update in Data Sync setup

### ISSUE THREAD

**Issue by nvwieren** [mendix/RestServices#59]
I am prototyping the Data Synchronization setup for a loosely coupled Mendix modules based application. 
To keep it simple: 
I have two modules (SourceModule, TargetModule), both with a **Person** and a **PersonTransient** object. 
The source Person object is configured as a service in the RestServices module incl. the option **Enable change log**. Java action **followChanges** is used to consume the changes in the SourceModule entity.

Now when I create a Person object in the SourceModule, the data is picked up by the followChanges subscription just fine and processed by an UpdatePerson microflow. But with every refresh of followChanges, I keep getting the following message: 

*Received revision (1) is smaller than the latest known revision (1), probably the collections are out of sync?*

Any idea on why this keeps happening?

**Comment by mweststrate** [comment]
Hi Nick,

Can you elaborate a bit on your issue? How / when do you trigger `followChanges`? Please note that you only need to trigger `followChanges` once in your app, from that point on, your app will keep tracking the remove application.

**Comment by mweststrate** [comment]
Closed for inactivity
