### ISSUE TITLE
Question: Why HttpClient 3.1

### ISSUE THREAD

**Issue by barrit** [mendix/RestServices#61]
I'm already consuming rest services in my project and I'm using HttpClient 4.4. I was wondering why this module uses the end-of life commons httpclient ( http://hc.apache.org/httpclient-3.x/ )

**Comment by mweststrate** [comment]
If I remember correctly this is mainly because of compatibility with Mendix
4.x, which ships with httpclient 3 and doesn't support OSGI containers.
