### ISSUE TITLE
JSON responses starting with '['

### ISSUE THREAD

**Issue by hodch01** [mendix/RestServices#67]
Rest Module is not accepting a JSON response starting with a '[' 

java.lang.RuntimeException: java.lang.IllegalArgumentException: Response body does not seem to be a valid JSON Object. A JSON object starts with '{' but found: [{"identifier": "Fastway", "name": "Fastway"}, {"identifier": "Royal Mail", "name": "Royal Mail"}, {"identifier": "DHL", "name": "DHL"}, {"identifier": "Deutsche Post", "name": "Deutsche Post"}, {"identifier": "PostNL", "name": "PostNL"}, {"identifier": "MRW", "name": "MRW"}, {"identifier": "DX", "name": "DX"}]

**Comment by mweststrate** [comment]
Use getCollection instead, as your service returns a list of objects.

**Comment by hodch01** [comment]
Thanks :)
