### ISSUE TITLE
Java compile errors in Mx5.21.1 and Rest V1.5

### ISSUE THREAD

**Issue by RCatersels** [mendix/RestServices#71]
I am upgrading a project from 5.16.1 to 5.21.1 and experience java compile errors. The the error is below. Any suggestion on how to fix this?

Regards,

Ronald

Buildfile: C:\Users\Ronald\Documents\Mendix\HU - RGW-main\deployment\build_core.xml

compile:
    [javac] Compiling 1213 source files to C:\Users\Ronald\Documents\Mendix\HU - RGW-main\deployment\run\bin
    [javac] C:\Users\Ronald\Documents\Mendix\HU - RGW-main\javasource\restservices\publish\RestServiceHandler.java:251: warning: '_' used as an identifier
    [javac] 			String _) {
    [javac] 			       ^
    [javac]   (use of '_' as an identifier might not be supported in releases after Java SE 8)
    [javac] C:\Users\Ronald\Documents\Mendix\HU - RGW-main\javasource\saml20\implementation\security\SessionManager.java:184: error: cannot find symbol
    [javac] 				response.addHeader(RequestHandler.CSRF_TOKEN_HEADER, (String) session.getData().get(Session.CSRF_TOKEN_KEY));
    [javac] 				                                                                                           ^
    [javac]   symbol:   variable CSRF_TOKEN_KEY
    [javac]   location: class Session
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 1 warning

**Comment by RCatersels** [comment]
Never mind, I must have had my eyes still closed. It's the LDAP that is giving problems.

**Comment by mweststrate** [comment]
:)
