### ISSUE TITLE
Add support for HTTP method PATCH 

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/RestServices#75]
To support OData 
[http://www.odata.org/getting-started/basic-tutorial/#update](http://www.odata.org/getting-started/basic-tutorial/#update)
We require to use the Http Method PATCH

However this require the httpclient to be update to version newer the 4.2

**Comment by mweststrate** [comment]
This is (most probably) a feature request with lots of impact, I suggest filing a ticket at support.mendix.com

**Comment by Andries-Smit** [comment]
PATCH Method can be found in the Mendix 6.6.0 release.
