### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by rdekkers** [mendix/RestServices#76]
Is there a clean way to support CORS?

**Comment by JelleDekker** [comment]
I'm also very curious about this

**Comment by ako** [comment]
What is the use case for this?

Verstuurd vanaf mijn iPhone

**Comment by JelleDekker** [comment]
In my case, another application wants to use our data by calling the rest-service client-side from their application, via https.

**Comment by rdekkers** [comment]
The Rest client calls services outside the domain of the code base. If the client requires CORS support (e.g. javascript in a browser) then there will be preflights with method OPTIONS.

**Comment by ako** [comment]
You mean a non Mendix JavaScript rest client? Not the rest module as a client?

We will not add this short term to the rest module. We are working on native rest in the Mendix platform. We can consider it there, but will not be first priority.

If you need if, you can of course add the functionality yourself in the source on github.

Verstuurd vanaf mijn iPhone

**Comment by JelleDekker** [comment]
I mean a published rest service via the Mendix rest module, which is called from a non-Mendix client yes.

I'll look in the source code then, thanks. Native rest in Mendix sounds exiting.

**Comment by JelleDekker** [comment]
What is the roadmap/timeframe for native REST in Mendix, and will it include CORS?

**Comment by mweststrate** [comment]
Note that you should be able to set your own CORS headers on individual microflows published by the Rest services module using `setResponseHeader` java action. For the explanation of CORS headers see https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

You could also consider fixing this on nginx level which might be a more appropriate place, depending on your hosting solution and acceptability of security implications.
