### ISSUE TITLE
Order of primitives and sub structure

### ISSUE THREAD

**Issue by nvwieren** [mendix/RestServices#99]
I've published a REST microflow returning a root object with several sub structures. One of these contains 2 attributes and a reference to a deeper substructure.

Although not important functionally; is it possible to make sure primitives are serialized first and references after that?

**Comment by mweststrate** [comment]
Note that in the JSON standard there is no ordering of attributes, and it
shouldn't matter for the consumer in which order they arrive. { x: 1, y: 2
} should be treated exactly the same as { y: 2, x: 1}

Op do 22 feb. 2018 om 10:49 schreef Nick van Wieren <
notifications@github.com>:

**Comment by nvwieren** [comment]
Hence my comments - "not important functionally" - I was wondering if there is any possibility to show attributes first, references last just for aesthetic purposes.
